### ISSUE TITLE
Cannot run site locally on macOS using Multipass and dotrun snap

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/ubuntu.com#8243]
- I followed [@hatched's instructions](https://fromanegg.com/post/2020/02/28/use-ubuntu-on-mac-os-with-multipass/) and have setup Multipass on my macOS machine.
- I shell into my Multipass instance and clone this repo
- I cd into the project root and run `docker-compose up -d`

I hit this error: 

`ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.

I then run that suggested command, and see this message;

`Docker machine "default" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.`

I then run the suggested action `docker-machine create default` and I get this error:

`Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"`

Now I be like `¯\_(ツ)_/¯`

**Comment by carkod** [comment]
I used [this solution to work around it](https://github.com/docker/machine/issues/4590#issuecomment-449945668)

**Comment by barrymcgee** [comment]
@carkod So I recreated my Multipass instance using 18.04 and ran through all the setup steps again, this time installing docker-machine using curl instead of via a snap - but still hit the same error when running `dotrun` in the root of ubuntu.com

<img width="1063" alt="Screenshot 2020-09-10 at 11 10 55" src="https://user-images.githubusercontent.com/505570/92716307-8efe7800-f356-11ea-8cde-edb4f0d78302.png">

As a wider point, we seem to be now in a place having moved from `./run` to `dotrun` where this repo can only be easily run locally by developers running Linux. The README does not even explicit state that in the Getting Started.

**Comment by carkod** [comment]
> @carkod So I recreated my Multipass instance using 18.04 and ran through all the setup steps again, this time installing docker-machine using curl instead of via a snap - but still hit the same error when running `dotrun` in the root of ubuntu.com
> 
> <img alt="Screenshot 2020-09-10 at 11 10 55" width="1063" src="https://user-images.githubusercontent.com/505570/92716307-8efe7800-f356-11ea-8cde-edb4f0d78302.png">
> 
> As a wider point, we seem to be now in a place having moved from `./run` to `dotrun` where this repo can only be easily run locally by developers running Linux. The README does not even explicit state that in the Getting Started.

Ok. But that is something else. Did you guys manage to install docker-compose with the workaround I provided? 

This issue with docker-compose is only going to happen with `ubuntu.com` project. Other projects don't need a database, so you don't even need docker-compose

**Comment by barrymcgee** [comment]
> Did you guys manage to install docker-compose with the workaround I provided?

No, your link was to install docker-machine, not docker-compose.

I setup a new multipass instance again, and installed docker-compose using cURL. 

Running `docker-compose up -d` still throws an error.

```bash
docker-compose --version
docker-compose version 1.27.0, build 980ec85b
ubuntu@ubuntu:~/code/ubuntu.com$ docker-compose up -d
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 403, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 205, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 228, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 188, in __init__
  File "docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[4119] Failed to execute script docker-compose
ubuntu@ubuntu:~/code/ubuntu.com$ 
```
