### ISSUE TITLE
/advantage 500 - bad key lookup on renewal

### ISSUE THREAD

**Issue by ajbeattie** [canonical-web-and-design/ubuntu.com#8626]
This may be the result of a weird account state on the back end, but nevertheless, when logging into /advantage with my sso account, I get:

```
Traceback (most recent call last):
  File "/home/multipass/code/ubuntu.com/.venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/multipass/code/ubuntu.com/.venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/multipass/code/ubuntu.com/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/multipass/code/ubuntu.com/.venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/multipass/code/ubuntu.com/.venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/multipass/code/ubuntu.com/.venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/multipass/code/ubuntu.com/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/multipass/code/ubuntu.com/.venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/multipass/code/ubuntu.com/.venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/multipass/code/ubuntu.com/webapp/views.py", line 535, in advantage_view
    advantage, contract["contractInfo"]
  File "/home/multipass/code/ubuntu.com/webapp/views.py", line 818, in make_renewal
    if renewal["status"] == "processing":
KeyError: 'status'
```

The `make_renewal` method in question ([here](https://github.com/canonical-web-and-design/ubuntu.com/blob/advantage-shop/webapp/views.py#L790)) accesses several fields on renewals which are not guaranteed to exist.

It's possible this behavior is okay, and that we should show a 500 if there's an invalid renewal state (as that would most likely indicate a true server error). On the other hand, we could ignore these and only show renewals with valid state.

Thoughts @alnvdl and @jaycee?

**Comment by ajbeattie** [comment]
This actually appears to be fixed now! Closing

**Comment by ajbeattie** [comment]
Not fixed - reopening.

**Comment by jaycee** [comment]
@ajbeattie--was this b/c the renewal was created badly (e.g. a bug in renewal handling) or b/c the frontend is looking for fields that a normally processed renewal might not have?

In either event I don't think a server error is right; fields should be checked before being accessed, or the exception should be caught. At a minimum I would expect a reasonable error message to be logged somewhere we can see it rather than just a traceback, and the user to be able to see *something* rather than the server error page.

**Comment by ajbeattie** [comment]
@jaycee the renewal was created early in the renewal development process, so it's missing fields that should be on renewals now - however, all of the renewal fields are `omitempty` in the backend.

Also, I agree that a bad renewal state should not completely prevent access to `/advantage`

**Comment by alnvdl** [comment]
So, the renewal that @ajbeattie is using is clearly wrong (it seems to be one of the first renewals to ever exist), and should not be supported (it does not have a status set), or at least not displayed.

That being said, this block here could `try`/`except` and log a message, so it doesn't crash on a faulty renewal (or on a faulty parsing of a valid renewal).
